### ISSUE TITLE
other react-based sliders

### ISSUE THREAD

**Issue by timelyportfolio** [JohnCoene/reactslider#1]
I have a couple little basic trials with some other sliders, such as [rheostat](https://github.com/airbnb/rheostat), [material-ui](https://github.com/glin/reactable/issues/9#issuecomment-556920895), and [antd-slider](https://ant.design/components/slider/), if you have interest.

**Comment by JohnCoene** [comment]
rheostat looks like what I’m after. Do you have the R integration?

**Comment by timelyportfolio** [comment]
@JohnCoene nothing formal yet, but I likely will have something tonight or sometime this week.

**Comment by JohnCoene** [comment]
Ok, looking forward!

**Comment by uriahf** [comment]
@timelyportfolio are there any examples available? I really need range sliders for reactable!

**Comment by timelyportfolio** [comment]
@uriahf do you want them in the header cells or outside of the table?

**Comment by uriahf** [comment]
In the header cells, thank you!
